export { ReactComponent as EditIcon } from './edit.svg'
export { ReactComponent as DeleteIcon } from './delete.svg'
export { ReactComponent as ModifyIcon } from './modify.svg'
export { ReactComponent as CancleIcon } from './cancle.svg'
export { ReactComponent as SubmitIcon } from './submit.svg'
